[workspace]
members = ["sink"]

[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kernel"
test = false
doctest = false
bench = false

[dependencies]
sink = { path = "sink" }
