[package]
name = "rosti"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["kernel"]
resolver = "2"

[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "0.11" 
